# Generated by Django 3.0.6 on 2020-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0004_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource', models.FileField(upload_to='files')),
                ('text', models.CharField(max_length=300)),
            ],
        ),
    ]
