# Generated by Django 3.0.6 on 2020-06-16 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0006_auto_20200615_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='resource',
        ),
        migrations.AddField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ads_images',
            name='resource',
            field=models.FileField(default='images/logo.png', upload_to='files'),
        ),
    ]
