# Generated by Django 3.0.6 on 2020-06-16 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educa', '0007_auto_20200615_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=300, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='company_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='company_names', to='educa.Company'),
        ),
    ]
